# the room-id of the matrix room or space to use as your "full user list"
parent_room: "!somerandomcharacters:server.tld"

# whether to encrypt rooms when using the room creation commands 
encrypt: False

# number of days of inactivity to be considered in the "warning zone"
warn_threshold_days: 30

# number of days of inactivity to be considered in the "danger zone"
kick_threshold_days: 60


# track messages? if false, will not track user activity timestamps. enable if you'd like to track
# inactive users in your community
track_messages: True

# track reactions? if false, will only track activity based on normal message events, but if true
# will update the user's last-active date when they add a reaction to a message
track_reactions: True

# list of users who can use administrative commands, these users will also be made room admins (PL100)
# in new rooms created with the create room commands
admins:
  - '@user1:server.tld'
  - '@user2:server.tld'

# list of users who should be invited to new rooms immediately (other bots perhaps)
invitees:
- "@mybot:server.tld"
- "@secondaryadmin:server.tld"

# auto-greet users in rooms with these messages
# map greeting messages to a room
# you can use {user} to reference the joining user in this message using a
# matrix.to link (rendered as a "pill" in element clients)
# html formatting is supported
greetings:
  generic: |
    Welcome {user}! Please be sure to read the topic for helpful links and information.
    Use <a href="https://google.com">Google</a> for all other queries ;)
  encrypted: |
    welcome {user}, this is an encrypted room, so you may not be able to see messages previously sent here. don't be
    alarmed.

# which of the above greetings should be used in which rooms? use the exact name of each greeting
# you've assigned, e.g. 'generic' or 'encrypted'. you must use the room ID here.
greeting_rooms:
  '!someroomid:server.tld': generic
  '!someotherroom:server.tld': generic
  '!myencryptedroomid:server.tld': encrypted

# add a room ID here to send a message to when someone joins the above rooms
# (optional)
notification_room: 

# message to send to the notification room when someone joins one of the above rooms:
join_notification_message: |
  User <code>{user}</code> has joined <code>{room}</code>.
