# the room-id of the matrix room or space to use as your "full user list"
parent_room: "!somerandomcharacters:server.tld"

# whether to encrypt rooms when using the room creation commands 
encrypt: False

# number of days of inactivity to be considered in the "warning zone"
warn_threshold_days: 30

# number of days of inactivity to be considered in the "danger zone"
kick_threshold_days: 60


# track messages? if false, will not track user activity timestamps. enable if you'd like to track
# inactive users in your community
track_messages: True

# track reactions? if false, will only track activity based on normal message events, but if true
# will update the user's last-active date when they add a reaction to a message
track_reactions: True

# list of users who can use administrative commands, these users will also be made room admins (PL100)
# in new rooms created with the create room commands
admins:
  - '@user1:server.tld'
  - '@user2:server.tld'

# list of users who should be invited to new rooms immediately (other bots perhaps)
invitees:
- "@mybot:server.tld"
- "@secondaryadmin:server.tld"
